<Project>

  <PropertyGroup>
    <!-- See https://www.nuget.org/packages/JetBrains.ReSharper.SDK -->
    <!-- Keep in sync with ProductVersion in gradle.properties -->
    <SdkVersion>2025.3.0.1</SdkVersion>

    <Title>AutoMapper.FindUsage</Title>
    <Description>ReSharper plugin for easy navigation from destination properties to source properties in AutoMapper mappings.</Description>

    <Authors>Sergey Rogatnev</Authors>
    <Copyright>Copyright $([System.DateTime]::Now.Year) Sergey Rogatnev</Copyright>
    <PackageTags>resharper plugin automapper navigation find-usages</PackageTags>

    <PackageProjectUrl>https://github.com/Backs/AutoMapper.FindUsage</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

</Project>
